Repository bbc/bigscreen-player, pull requests merged in 2020-10, with the labels that each got.

#171 Remove usage of TAL device
  README.md
  development/index.js
  script-test/bigscreenplayertest.js
  script-test/mediasourcestest.js
  script-test/playbackstrategies/legacyplayeradaptortest.js
  script-test/playbackstrategies/modifiers/cehtmltests.js
  script-test/playbackstrategies/modifiers/html5tests.js
  script-test/playbackstrategies/modifiers/live/restartabletest.js
  script-test/playbackstrategies/modifiers/live/seekabletest.js
  script-test/playbackstrategies/modifiers/samsungmapletest.js
  script-test/playbackstrategies/modifiers/samsungstreaming2015test.js
  script-test/playbackstrategies/modifiers/samsungstreamingtest.js
  script-test/playbackstrategies/msestrategytest.js
  script-test/playbackstrategies/nativestrategytest.js
  script-test/playbackstrategies/talstrategytest.js
  script/bigscreenplayer.js
  script/mediasources.js
  script/mockbigscreenplayer.js
  script/models/playbackstrategy.js
  script/playbackstrategy/hybridstrategy.js
  script/playbackstrategy/legacyplayeradapter.js
  script/playbackstrategy/mockstrategy.js
  script/playbackstrategy/modifiers/cehtml.js
  script/playbackstrategy/modifiers/html5.js
  script/playbackstrategy/modifiers/live/restartable.js
  script/playbackstrategy/modifiers/live/seekable.js
  script/playbackstrategy/modifiers/samsungmaple.js
  script/playbackstrategy/modifiers/samsungstreaming.js
  script/playbackstrategy/modifiers/samsungstreaming2015.js
  script/playbackstrategy/msestrategy.js
  script/playbackstrategy/nativestrategy.js
  script/playbackstrategy/talstrategy.js
  script/playercomponent.js
Labels: has NO user facing change, semver major

#172 Resizer
  script-test/bigscreenplayertest.js
  script-test/resizertest.js
  script/bigscreenplayer.js
  script/resizer.js
Labels: has NO user facing change, semver minor

#173 Mock update
  script-test/bigscreenplayertest.js
  script/mockbigscreenplayer.js
Labels: has NO user facing change, semver patch

#174 IPLAYERTVV1 10894 Call Success Callback when BSP Ready
  script-test/bigscreenplayertest.js
  script-test/readyhelpertest.js
  script/bigscreenplayer.js
  script/readyhelper.js
Labels: has a user facing change, semver minor
