Repository bbc/bigscreen-player, pull requests merged in 2021-09, with the labels that each got.

#233 make @bbc/honey-badger-core code owners
  CODEOWNERS
Labels: semver prerelease, has NO user facing change

#237 Make subtitle header XML split more general
  script-test/subtitles/imscsubtitles.js
  script/subtitles/imscsubtitles.js
Labels: semver minor, has NO user facing change

#239 Update Security Updates
  package-lock.json
  package.json
Labels: semver patch, has NO user facing change

#194 Replace Travis with Github Actions
  .github/workflows/npm-publish.yml
  .github/workflows/pull-requests.yml
  .nvmrc
  .travis.yml
  README.md
Labels: semver patch, has NO user facing change

#240 Add simple GitHub Pages splash page
  docs/bsp-logo.png
  docs/favicon-32x32.png
  docs/index.html
  docs/styles.css
Labels: semver patch, has a user facing change
