Repository bbc/bigscreen-player, pull requests merged in 2021-03, with the labels that each got.

#197 BaseUrl failover for CDNs without a BaseUrl in the manifest (MSE Strategy)
  script-test/manifest/manifestmodifiertest.js
  script/manifest/manifestmodifier.js
Labels: has NO user facing change, semver minor

#201 Live subtitles
  script-test/subtitles/imscsubtitles.js
  script-test/subtitles/legacysubtitles.js
  script-test/subtitles/subtitles.js
  script/bigscreenplayer.js
  script/subtitles/imscsubtitles.js
  script/subtitles/legacysubtitles.js
  script/subtitles/subtitles.js
  script/utils/timeutils.js
Labels: has a user facing change, semver minor

#202 Added readme changes for subtitle work
  README.md
Labels: has NO user facing change, semver patch
