Repository bbc/bigscreen-player, pull requests merged in 2021-05, with the labels that each got.

#200 Update to SMP Dash 3.2
  package-lock.json
  package.json
  script-test/playbackstrategies/msestrategytest.js
  script/playbackstrategy/msestrategy.js
Labels: bug fix, dependencies, has NO user facing change, semver minor

#215 Ability to set/get playback rate
  script-test/bigscreenplayertest.js
  script-test/playbackstrategies/basicstrategytest.js
  script-test/playbackstrategies/legacyplayeradaptortest.js
  script-test/playbackstrategies/modifiers/html5tests.js
  script-test/playbackstrategies/msestrategytest.js
  script-test/playercomponenttest.js
  script/bigscreenplayer.js
  script/mockbigscreenplayer.js
  script/playbackstrategy/basicstrategy.js
  script/playbackstrategy/legacyplayeradapter.js
  script/playbackstrategy/mockstrategy.js
  script/playbackstrategy/modifiers/html5.js
  script/playbackstrategy/modifiers/samsungmaple.js
  script/playbackstrategy/modifiers/samsungstreaming.js
  script/playbackstrategy/modifiers/samsungstreaming2015.js
  script/playbackstrategy/msestrategy.js
  script/playercomponent.js
Labels: has NO user facing change, semver minor

#217 NPM Audit: Update Dependencies
  package-lock.json
Labels: has NO user facing change, semver patch
