Repository bbc/bigscreen-player, pull requests merged in 2024-10, with the labels that each got.

#354 Fix broken anchor link in subtitles tutorial
  docs/tutorials/Subtitles.md
Labels: semver prerelease

#355 Augment onManifestLoaded plugin with the manifest load time
  src/playbackstrategy/msestrategy.js
Labels: semver patch

#357 Added manifest load count
  src/playbackstrategy/msestrategy.js
Labels: semver patch

#356 Plugin for `onQualityChangeRequested`
  docs/tutorials/Plugins.md
  src/playbackstrategy/msestrategy.js
  src/plugins.js
Labels: semver minor

#359 Docs update - Add resetMSEPlayer override setting
  docs/tutorials/02-settings-and-overrides.md
Labels: semver minor

#358 BADGERS-427 Abort Retrieve Manifest When Calling Reset
  package-lock.json
  package.json
Labels: semver patch
