Repository bbc/bigscreen-player, pull requests merged in 2025-04, with the labels that each got.

#377 Bump Dash to v4.7.3-5
  package-lock.json
  package.json
Labels: semver patch

#378 Add `target-latency` and `current-latency` to Chronicle (Update of #361)
  package-lock.json
  package.json
  src/debugger/chronicle.ts
  src/playbackstrategy/msestrategy.js
  src/playbackstrategy/msestrategy.test.js
Labels: semver minor

#380 Add audio-quality, video-quality, and max-bitrate to the on-screen debugger
  src/debugger/chronicle.test.ts
  src/debugger/chronicle.ts
  src/debugger/debugtool.test.ts
  src/debugger/debugtool.ts
  src/debugger/debugview.ts
  src/debugger/debugviewcontroller.test.ts
  src/debugger/debugviewcontroller.ts
  src/models/mediakinds.ts
  src/playbackstrategy/msestrategy.js
  src/playbackstrategy/msestrategy.test.js
Labels: enhancement, semver minor

#381 Add new Low Latency Catchup Algorithm
  package-lock.json
  package.json
Labels: semver minor
