Repository bbc/bigscreen-player, pull requests merged in 2025-03, with the labels that each got.

#371 fix(imsc): subtitle startup race condition
  src/subtitles/imscsubtitles.js
  src/subtitles/imscsubtitles.test.js
Labels: semver patch

#365 BADGERS-575: [BREAKING] Audio Described Unification
  docs/tutorials/00-getting-started.md
  docs/tutorials/Audio Description.md
  eslint.config.js
  package-lock.json
  package.json
  src/bigscreenplayer.js
  src/bigscreenplayer.test.js
  src/mediasources.test.ts
  src/mediasources.ts
  src/mockbigscreenplayer.js
  src/playbackstrategy/legacyplayeradapter.js
  src/playbackstrategy/legacyplayeradapter.test.js
  src/playbackstrategy/modifiers/cehtml.js
  src/playbackstrategy/modifiers/cehtml.test.js
  src/playbackstrategy/modifiers/html5.js
  src/playbackstrategy/modifiers/html5.test.js
  src/playbackstrategy/modifiers/live/playable.js
  src/playbackstrategy/modifiers/live/playable.test.js
  src/playbackstrategy/modifiers/live/restartable.js
  src/playbackstrategy/modifiers/live/restartable.test.js
  src/playbackstrategy/modifiers/live/seekable.js
  src/playbackstrategy/modifiers/live/seekable.test.js
  src/playbackstrategy/modifiers/samsungmaple.js
  src/playbackstrategy/modifiers/samsungmaple.test.js
  src/playbackstrategy/modifiers/samsungstreaming.js
  src/playbackstrategy/modifiers/samsungstreaming.test.js
  src/playbackstrategy/modifiers/samsungstreaming2015.js
  src/playbackstrategy/modifiers/samsungstreaming2015.test.js
  src/playbackstrategy/msestrategy.js
  src/playbackstrategy/msestrategy.test.js
  src/playbackstrategy/nativestrategy.js
  src/playercomponent.js
  src/playercomponent.test.js
  src/types.ts
Labels: semver major

#372 Fix Docs Build
  jsdoc.conf.json
  package-lock.json
  package.json
  src/bigscreenplayer.js
  src/playercomponent.js
Labels: bug fix, semver patch

#373 Add Guards Around Setting `cached.currentTime`
  src/playbackstrategy/msestrategy.js
  src/playbackstrategy/msestrategy.test.js
Labels: semver patch

#374 Use the Correct Name for Functions in MockBigScreenPlayer
  src/mockbigscreenplayer.js
Labels: semver patch

#375 Add Correct Initial Audio Settings
  src/playbackstrategy/msestrategy.js
  src/playbackstrategy/msestrategy.test.js
Labels: semver minor

#376 Add releasinator config file
  .releasinator.json
Labels: semver patch
